-- Student numbers and invoice numbers were generated by counting existing
-- rows and adding one, which races under concurrent requests (two
-- approvals/invoices created at nearly the same time can get the same
-- number). Replace with an atomic counter table + function.
create table if not exists number_sequences (
  key        text primary key,
  last_value integer not null default 0
);

alter table number_sequences enable row level security;
-- RLS enabled with no policies: only the function below (security definer)
-- or the service-role client can touch this table.

create or replace function next_sequence_number(seq_key text)
returns integer
language plpgsql
security definer
as $$
declare
  result integer;
begin
  insert into number_sequences (key, last_value)
  values (seq_key, 1)
  on conflict (key) do update set last_value = number_sequences.last_value + 1
  returning last_value into result;
  return result;
end;
$$;

grant execute on function next_sequence_number(text) to authenticated, service_role;
