-- Seeds the published curriculum (modules) for each program.
-- Run this in the Supabase SQL editor after migration_006_module_fields.sql.

-- ─── Certificate in Biblical Studies (one year, 30 credits) ────────────────
insert into courses (title, code, description, credits, program_id) values
  ('Who is God', 'CBS-001', 'This module teaches on the origin and nature of God and explores the many names through which He reveals Himself in Scripture. It forms the foundation of theology and helps students understand God''s identity, attributes, and relationship with His creation.', 3, (select id from programs where name = 'Certificate')),
  ('Christology', 'CBS-002', 'Theology cannot be complete without understanding the person and work of Jesus Christ. This module focuses on the birth, ministry, death, resurrection, and mission of Jesus Christ on earth, emphasizing His divine and human natures and their significance in the redemption plan.', 3, (select id from programs where name = 'Certificate')),
  ('Bible Expository', 'CBS-003', 'This module equips students with the skills to interpret and explain Scripture accurately. It focuses on studying the Bible systematically, understanding its context, and presenting its message clearly to others. Students learn practical methods for preaching and teaching God''s Word effectively.', 3, (select id from programs where name = 'Certificate')),
  ('The Blood Covenant', 'CBS-004', 'This module unveils the significance of the blood covenant throughout the Bible—from Old Testament sacrifices to the New Covenant through Christ. Students learn the power, promises, and responsibilities that come with being in covenant with God.', 3, (select id from programs where name = 'Certificate')),
  ('Gifts of the Holy Spirit', 'CBS-005', 'The Holy Spirit is a special gift from God who guides, teaches, and strengthens believers. For students, He is a source of wisdom, courage, and good character, helping them to succeed both spiritually and academically.', 3, (select id from programs where name = 'Certificate')),
  ('Power of Praise and Worship', 'CBS-006', 'This module explores the spiritual importance and transforming power of praise and worship. Students learn how true worship connects humanity to God''s presence, breaks spiritual barriers, and brings deliverance and intimacy with God.', 3, (select id from programs where name = 'Certificate')),
  ('Understanding and Releasing Your Potential', 'CBS-007', 'This module empowers students to discover their God-given purpose, talents, and abilities. It teaches how to identify, develop, and release one''s potential for kingdom service and personal growth according to biblical principles.', 3, (select id from programs where name = 'Certificate')),
  ('School of Prayer', 'CBS-008', 'This module provides a deep understanding of prayer as communication with God. It examines various types of prayer, principles of effective prayer, and how to develop a consistent, powerful prayer life that brings results.', 3, (select id from programs where name = 'Certificate')),
  ('Evangelism', 'CBS-009', 'This module trains students to effectively share the Gospel with others. It teaches the biblical basis for evangelism, personal witnessing techniques, and the importance of fulfilling the Great Commission with compassion and wisdom.', 3, (select id from programs where name = 'Certificate')),
  ('Foundation of Faith and Prayer', 'CBS-010', 'This foundational module strengthens the believer''s faith through the Word of God and establishes prayer as a lifestyle. It emphasizes the importance of trusting God, standing on His promises, and building a faith-based relationship with Him.', 3, (select id from programs where name = 'Certificate'))
on conflict (code) do nothing;

-- ─── Diploma in Biblical Studies (one year, 66 credits) ─────────────────────
insert into courses (title, code, description, credits, program_id) values
  ('Who is God?', 'DBS-011', 'An advanced exploration of God''s attributes, character, and divine nature. This module deepens understanding of His sovereignty, holiness, love, and justice, providing a solid theological foundation for ministry and Christian living.', 3, (select id from programs where name = 'Diploma')),
  ('Christology', 'DBS-012', 'A comprehensive study of the person and work of Jesus Christ, focusing on His divinity and humanity, incarnation, earthly ministry, miracles, teachings, atoning death, resurrection, ascension, and second coming. The module also examines Christ''s demonstration of healing, spiritual gifts, and the empowerment of believers through the Holy Spirit. Students explore how His redemptive work fulfills God''s eternal plan and forms the foundation for Christian ministry, healing, and the operation of spiritual gifts today. Emphasis is placed on practical application to equip students for effective teaching, service, and pastoral care.', 3, (select id from programs where name = 'Diploma')),
  ('Pneumatology', 'DBS-013', 'This module focuses on the doctrine of the Holy Spirit—His person, work, and role in the believer''s life and the Church. Students explore topics such as the baptism of the Holy Spirit, fruit of the Spirit, and spiritual empowerment for service.', 3, (select id from programs where name = 'Diploma')),
  ('Old and New Testament Survey', 'DBS-014', 'Testament Survey is very important in Theology because it helps students understand the whole message of the Bible and God''s plan for humanity.', 3, (select id from programs where name = 'Diploma')),
  ('Major and Minor Prophets', 'DBS-015', 'In Theology, the study of the Major and Minor Prophets helps students understand how God spoke to His people through chosen messengers in the Old Testament. Prophets were men called by God to reveal His will, warn against sin, and give hope for the future.', 3, (select id from programs where name = 'Diploma')),
  ('Demonology', 'DBS-016', 'This module studies the origin, nature, and operation of demonic forces. Students learn biblical principles for spiritual warfare, authority in Christ, and how to overcome demonic influences through the power of the Holy Spirit.', 3, (select id from programs where name = 'Diploma')),
  ('Church History', 'DBS-017', 'A study of the development of the Christian Church from its birth in the Book of Acts to the modern era. Students explore key movements, leaders, revivals, and how historical events have shaped the faith and doctrines practiced today.', 3, (select id from programs where name = 'Diploma')),
  ('Dispensations', 'DBS-018', 'This module explains God''s dealings with humanity through different dispensations or time periods. It helps students understand the unfolding of God''s redemptive plan and how each era reveals His grace and purpose for mankind.', 3, (select id from programs where name = 'Diploma')),
  ('Character and Personality', 'DBS-019', 'This module emphasizes personal transformation through biblical character development. Students learn how to cultivate Christ-like attributes, integrity, and discipline essential for effective ministry and leadership.', 3, (select id from programs where name = 'Diploma')),
  ('Ministry of Prayer', 'DBS-020', 'An in-depth study of prayer as the engine of ministry. Students learn the intercessory role of a minister, how to pray strategically for revival, and how prayer sustains both personal and corporate ministry success.', 3, (select id from programs where name = 'Diploma')),
  ('Hermeneutics', 'DBS-021', 'This module equips students with foundational principles of biblical interpretation, teaching historical, grammatical, and contextual approaches to exegesis for accurate understanding and application of Scripture. Emphasis is placed on avoiding misinterpretation and developing sound interpretation skills for ministry and personal study.', 3, (select id from programs where name = 'Diploma')),
  ('Homiletics', 'DBS-022', 'This module introduces students to the art and discipline of sermon preparation and delivery. Students learn how to construct biblical messages, develop sermon outlines, communicate effectively to diverse audiences, and minister with clarity and confidence. Focus areas include sermon structure, voice projection, delivery styles, and Spirit-led preaching.', 3, (select id from programs where name = 'Diploma')),
  ('Church Management and Administration', 'DBS-023', 'This practical module equips students with leadership and organizational skills for effective church governance. Topics include planning, delegation, financial stewardship, team building, and strategic decision-making.', 3, (select id from programs where name = 'Diploma')),
  ('Pastoral Leadership', 'DBS-024', 'This module develops leadership qualities essential for shepherding God''s people. It covers pastoral ethics, counseling, vision casting, conflict resolution, and the responsibilities of a spiritual leader.', 3, (select id from programs where name = 'Diploma')),
  ('Hamartiology', 'DBS-025', 'A theological study of sin—its origin, nature, and consequences. Students learn how sin separates humanity from God and the biblical solution through repentance and redemption in Christ.', 3, (select id from programs where name = 'Diploma')),
  ('Symbolisms', 'DBS-026', 'This module explores the meanings behind biblical symbols, types, and shadows found throughout Scripture. Students learn how these symbols point to Christ and reveal deeper truths about God''s plan of salvation.', 3, (select id from programs where name = 'Diploma')),
  ('Evangelism', 'DBS-027', 'A continuation of evangelism studies at an advanced level. Students gain deeper understanding of evangelistic strategies, cross-cultural missions, and how to impact communities and nations with the Gospel.', 3, (select id from programs where name = 'Diploma')),
  ('Praise and Worship', 'DBS-028', 'This module emphasizes worship as a lifestyle, not just an activity. Students learn the theology, principles, and spiritual dimensions of true worship that brings transformation and aligns believers with God''s presence.', 3, (select id from programs where name = 'Diploma')),
  ('Christian Counseling', 'DBS-029', 'This module introduces Christian counseling principles grounded in biblical truth. Students examine emotional, spiritual, and relational issues from a scriptural perspective while developing practical skills for pastoral care, crisis support, discipleship, and ethical ministry practice.', 3, (select id from programs where name = 'Diploma')),
  ('Ministerial Ethics and Church Etiquette', 'DBS-030', 'This module focuses on ethical standards, conduct, and decorum in Christian ministry. Students study principles of integrity, accountability, leadership character, respect for ecclesiastical order, and professional behavior in church settings. Topics include ministerial relationships, church protocol, administration, and representing Christ in public and private life.', 3, (select id from programs where name = 'Diploma')),
  ('Thesis and Presentation', 'DBS-THESIS', 'The student will write a 500-word thesis on a chosen module and present for 15 minutes before a panel of adjunct faculty.', 6, (select id from programs where name = 'Diploma'))
on conflict (code) do nothing;

-- ─── Bachelor of Theology (two years, 54 credits) ───────────────────────────
insert into courses (title, code, description, credits, program_id) values
  ('World Religions', 'ThB-031', 'This module provides an in-depth study of major world religions, including Islam, Hinduism, Buddhism, Judaism, and traditional belief systems. Students learn their historical origins, beliefs, practices, and how they compare and contrast with Christianity. The course equips students with knowledge to engage in respectful dialogue and evangelism across cultures and faiths.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Eschatology', 'ThB-032', 'This module focuses on the study of end-time events as revealed in Scripture. Topics include the second coming of Christ, the rapture, the millennial reign, final judgment, and the new heaven and earth. Students gain a balanced understanding of prophetic timelines and their relevance to Christian faith and daily living.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Doctrine of Angels', 'ThB-033', 'Students study the roles of holy angels as God''s messengers and agents, as well as the fall of Lucifer and the existence of fallen angels, deepening their understanding of spiritual realities.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Spirits and the Underworld - Altars', 'ThB-034', 'This module examines the spiritual dimension of unseen realms, including the concept of altars, covenants, and spiritual warfare. Students learn how altars influence human lives and territories and how to establish and maintain godly altars of prayer and worship that counter demonic influences.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Apocryphal Books', 'ThB-035', 'This module introduces the Apocryphal and Deuterocanonical books, exploring their historical background, themes, and theological implications. Students critically evaluate their relevance to biblical canon and understand why they are not included in most Protestant Bibles.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Humanism Vs. The Godhead', 'ThB-036', 'This module contrasts the modern philosophy of humanism with the biblical revelation of the Godhead—Father, Son, and Holy Spirit. Students examine how human-centered ideologies challenge divine truth and how to defend the supremacy of God''s authority and sovereignty in contemporary thought.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Customs of the Ancient and Geological Ages', 'ThB-037', 'This module offers a study of ancient cultural, social, and geographical contexts that shaped biblical times. Students learn about customs, laws, traditions, and geographical settings to gain deeper insight into the interpretation of Scripture and biblical narratives.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Ministerial Ethics and Church Ordinances', 'ThB-038', 'This module provides a framework for moral integrity and ethical conduct in ministry. It covers topics such as accountability, honesty, confidentiality, and the observance of church ordinances like baptism, communion, and marriage. Students are equipped to serve with excellence, character, and spiritual discipline.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Prophecy', 'ThB-039', 'This module trains students to understand, interpret, and operate within the prophetic dimension. It examines biblical prophecy, the role of prophets, the process of receiving revelation, and the responsibility of accurate prophetic delivery within the Church.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Leadership Skills', 'ThB-040', 'This module develops essential leadership principles for effective ministry and organizational impact. Students learn about vision development, decision-making, team leadership, communication, and emotional intelligence, preparing them to lead with wisdom, humility, and influence.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Hermeneutics', 'ThB-041', 'This module focuses on the principles and methods of biblical interpretation. Students learn how to study Scripture contextually, linguistically, and historically to draw accurate meaning and apply it practically in teaching and preaching.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Apologetics', 'ThB-042', 'This module equips students to defend the Christian faith intellectually and spiritually. It covers philosophical arguments, scriptural proofs, and modern challenges to Christianity, empowering students to articulate and defend biblical truth in an increasingly skeptical world.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('The Art of Counselling', 'ThB-043', 'This module trains students in the principles and practice of biblical counseling. It focuses on understanding human behavior, emotional healing, and providing Christ-centered guidance to individuals and families in need of spiritual, emotional, or moral support.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Theology of Missions', 'ThB-044', 'This module explores the biblical foundation, history, and strategies of Christian missions. Students learn the importance of spreading the Gospel globally, cultural sensitivity in mission work, and the believer''s role in fulfilling the Great Commission.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('The Tabernacle', 'ThB-045', 'This module provides a comprehensive study of the Tabernacle as revealed in the Old Testament and its prophetic significance in the New Covenant. Students explore the divine design, structure, furnishings, priestly functions, and the symbolic meaning behind every element. The course reveals how the Tabernacle foreshadowed Jesus Christ as the ultimate dwelling place of God among men. Through this study, students gain a deeper understanding of God''s holiness, the process of worship, and the believer''s journey into God''s presence.', 3, (select id from programs where name = 'Bachelor of Theology (B.Th.)')),
  ('Dissertation and Presentation', 'ThB-DISSERTATION', 'Student will write a 20,000 word count dissertation on any of these modules or a desired topic.', 9, (select id from programs where name = 'Bachelor of Theology (B.Th.)'))
on conflict (code) do nothing;

-- ─── Master of Theology (one year, 40 credits) ──────────────────────────────
insert into courses (title, code, description, credits, program_id) values
  ('Anointing and the Royal Priesthood', 'MTh-046', 'This module explores the biblical concept of the anointing and its connection to the royal priesthood of believers. Students study how God equips His servants with divine empowerment to fulfill their calling. The course emphasizes spiritual authority, consecration, and the believer''s role as both king and priest in advancing God''s Kingdom.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Apologetics', 'MTh-047', 'An advanced study of defending the Christian faith through sound reasoning, evidence, and scriptural truth. Students learn to address theological controversies, cultural skepticism, and philosophical objections to Christianity while upholding biblical integrity and clarity.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Skillful Leadership', 'MTh-048', 'This module develops advanced leadership skills rooted in biblical principles. It focuses on vision casting, strategic planning, mentoring, and leading with emotional and spiritual intelligence. Students learn to influence, inspire, and manage change within ministry and organizational contexts effectively.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Homiletics', 'MTh-049', 'A practical study of the art and discipline of preaching. Students learn sermon preparation, biblical exposition, delivery techniques, and audience engagement. The course emphasizes preaching that is both Spirit-led and theologically sound, bringing transformation to listeners.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Church in the 21st Century', 'MTh-050', 'This module examines the challenges and opportunities facing the modern Church. Topics include technology and ministry, globalization, cultural shifts, interfaith dynamics, and the Church''s role in addressing social issues. Students explore innovative approaches to remain relevant and effective in a changing world.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Denominationalism Vs. Saints', 'MTh-051', 'This module explores the origins and effects of denominational divisions within Christianity. Students study unity in the body of Christ and the biblical concept of "saints" as one universal Church. The course encourages a kingdom mindset that transcends denominational boundaries while respecting diversity of expression.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Counseling', 'MTh-052', 'This module offers advanced study in Christian counseling, integrating biblical theology with pastoral and psychological frameworks. Emphasis is placed on complex case analysis, ethical practice, spiritual discernment, and effective intervention in ministry and leadership settings.', 3, (select id from programs where name = 'Master of Theology (M.Th.)')),
  ('Dissertation and Presentation', 'MTh-DISSERTATION', 'Student will write a 40,000 word count dissertation on any of these modules or a desired topic and present for 20 minutes to a panel of adjuncts.', 19, (select id from programs where name = 'Master of Theology (M.Th.)'))
on conflict (code) do nothing;
